version: '3'

services:
  scylla:
    image: scylladb/scylla
    command: "--seeds 10.138.0.13"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      labels: [NODE_ROLE=SEED]
    ports:
        - 10000:10000
        - 9042:9042
        - 9160:9160
        - 7000:7000
        - 7001:7001
        - 7199:7199
